version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Node version check..."
      - node --version
      - echo "Installing dependencies..."
      - npm install
      
  pre_build:
    commands:
      - echo "Pre-build phase..."
      - node --version
      - npm --version
      
  build:
    commands:
      - echo "Building React application..."
      - npm run build
      - echo "Build completed successfully!"
      
  post_build:
    commands:
      - echo "Post-build phase completed"

artifacts:
  files:
    - '**/*'
  base-directory: build

cache:
  paths:
    - 'node_modules/**/*'